#cloud-config
groups:
  - ubuntu: [root,sys]
  - docker

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: ec
    gecos: ec
    shell: /bin/bash
    primary_group: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

write_files:
  - path: /home/cert.json
    content: |
      {
          "AccountTag"   : "${account}",
          "TunnelID"     : "${tunnel_id}",
          "TunnelName"   : "${tunnel_name}",
          "TunnelSecret" : "${secret}"
      }
  - path: /home/config.yml
    content: |
      tunnel: ${tunnel_id}
      credentials-file: /etc/cloudflared/cert.json
      logfile: /var/log/cloudflared.log
      loglevel: info
      
      ingress:
        # route wss to 8546
        - hostname: "${network}-ec-ws.baramio-nodes.com"
          service: ws://geth:8546
        # route rpc https to 8545
        - hostname: "${network}-ec-rpc.baramio-nodes.com"
          service: http://geth:8545
        # for healthcheck monitoring by the load balancer
        - hostname: "${tunnel_id}"
          service: http://geth:8545
        # everything else is invalid
        - service: http_status:404
  - path: /home/docker-compose.yaml
    content: |
      version: "3.4"
      x-logging: &logging
        logging:
          driver: json-file
          options:
            max-size: 10m
            max-file: "3"
      
      services:
        geth:
          restart: unless-stopped
          stop_grace_period: 3m
          image: ethereum/client-go:stable
          user: root
          container_name: geth
          volumes:
            - /mnt/${volume_name}:/var/lib/goethereum
            - /etc/localtime:/etc/localtime:ro
          ports:
            - 30303:30303/tcp
            - 30303:30303/udp
          expose:
            - 8545/tcp
            - 8546/tcp
            - 6060/tcp
          networks:
            - eth1
          <<: *logging
          entrypoint:
            - geth
            - --http
            - --http.addr
            - 0.0.0.0
            - --http.vhosts=*
            - --http.corsdomain=*
            - --http.api
            - web3,eth,net
            - --datadir
            - /var/lib/goethereum
            - --port
            - "30303"
            - --http.port
            - "8545"
            - --ws
            - --ws.addr
            - 0.0.0.0
            - --ws.origins=*
            - --ws.port
            - "8546"
            - --ws.api
            - web3,eth,net
            - --${network}
            - --metrics
            - --metrics.expensive
            - --rpc.txfeecap=0
            - --rpc.gascap=0
            - --pprof
            - --pprof.addr
            - 0.0.0.0
        cloudflared:
          container_name: cloudflared
          image: cloudflare/cloudflared:2022.2.0
          volumes:
            - /home/ec/execution_client/cloudflared/:/etc/cloudflared/
          command: 'tunnel --config /etc/cloudflared/config.yml run'
          user: root
          restart: unless-stopped
          networks:
            - eth1
          <<: *logging
      networks:
        eth1:
          driver: bridge
          driver_opts:
            com.docker.network.enable_ipv4: "true"

runcmd:
  - sudo apt remove --purge --assume-yes snapd
  - sudo apt update && sudo apt -y dist-upgrade
  - sudo apt install -y docker-compose
  - sudo systemctl enable --now docker
  - sudo timedatectl set-ntp no
  - sudo apt update && sudo apt install ntp -y
#  - sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
#  - sudo chmod +x /usr/local/bin/yq
#  - sudo apt-get install iptables net-tools -y
#  - gateway_ip=$(ps -ef | route -n | awk '$1 == "0.0.0.0" {print $2}')
#  - ip route add 169.254.169.254 via $gateway_ip dev eth0
#  - ip route change default via ${gateway_private_ip}
#  - yq d -i /etc/netplan/50-cloud-init.yaml network.ethernets.eth0.routes
#  - yq w -i /etc/netplan/50-cloud-init.yaml network.ethernets.eth1.routes[+].to 0.0.0.0/0
#  - yq w -i /etc/netplan/50-cloud-init.yaml network.ethernets.eth1.routes[0].via ${gateway_private_ip}
#  - netplan apply -debug
  - mkdir /home/ec/execution_client
  - mkdir /home/ec/execution_client/cloudflared
  - mv /home/cert.json /home/ec/execution_client/cloudflared/cert.json
  - mv /home/config.yml /home/ec/execution_client/cloudflared/config.yml
  - mv /home/docker-compose.yaml /home/ec/execution_client/docker-compose.yaml
  - chown ec:docker -R /home/ec
  - mkdir -p /mnt/${volume_name}
  - mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_${volume_name} /mnt/${volume_name}
  - echo '/dev/disk/by-id/scsi-0DO_Volume_${volume_name} /mnt/${volume_name} ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
  - cd /home/ec/execution_client && docker-compose up -d
