#cloud-config
groups:
  - ubuntu: [root,sys]
  - docker

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: ec
    gecos: ec
    shell: /bin/bash
    primary_group: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

runcmd:
  - sudo apt update && sudo apt -y dist-upgrade
  - sudo apt install -y docker-compose
  - sudo systemctl enable --now docker
  - sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
  - sudo chmod +x /usr/local/bin/yq
  - git clone https://github.com/eth-educators/eth-docker.git
  - mkdir /home/ec/eth-docker
  - mv /eth-docker/* /home/ec/eth-docker/
  - mv /eth-docker/.* /home/ec/eth-docker/
  - cp /home/ec/eth-docker/default.env /home/ec/eth-docker/.env
  - sed -i 's/COMPOSE_FILE=teku-base.yml:geth.yml/COMPOSE_FILE=geth.yml:ec-traefik.yml:traefik-cf.yml/g' /home/ec/eth-docker/.env
  - sed -i 's/EC_NETWORK=goerli/EC_NETWORK=${network}/g' /home/ec/eth-docker/.env
  - sed -i 's/DOMAIN=example.com/DOMAIN=baramio-nodes.com/g' /home/ec/eth-docker/.env
  - sed -i 's/DDNS_SUBDOMAIN=/DDNS_SUBDOMAIN=${ecws_host}/g' /home/ec/eth-docker/.env
  - sed -i 's/DDNS_PROXY=true/DDNS_PROXY=false/g' /home/ec/eth-docker/.env
  - sed -i 's/ACME_EMAIL=user@example.com/ACME_EMAIL=${cf_email}/g' /home/ec/eth-docker/.env
  - sed -i 's/CF_EMAIL=user@example.com/CF_EMAIL=${cf_email}/g' /home/ec/eth-docker/.env
  - sed -i 's/CF_API_TOKEN=SECRETTOKEN/CF_API_TOKEN=${cf_token}/g' /home/ec/eth-docker/.env
  - sed -i 's/EC_HOST=ec/EC_HOST=${ec_host}/g' /home/ec/eth-docker/.env
  - sed -i 's/EC_WS_HOST=ecws/EC_WS_HOST=${ecws_host}/g' /home/ec/eth-docker/.env
  - yq w -i /home/ec/eth-docker/geth.yml services.eth.image tianon/true
  - yq w -i /home/ec/eth-docker/geth.yml services.eth.restart --style=double no
  - yq w -i /home/ec/eth-docker/geth.yml 'services.execution.entrypoint[+]' ws.origins=*
  - sed -i 's/ws.origins/--ws.origins/g' /home/ec/eth-docker/geth.yml
  - yq w -i /home/ec/eth-docker/geth.yml 'services.execution.entrypoint[+]' ws.addr
  - yq w -i /home/ec/eth-docker/geth.yml 'services.execution.entrypoint[+]' 0.0.0.0
  - sed -i 's/ws.addr/--ws.addr/g' /home/ec/eth-docker/geth.yml
  - yq w -i /home/ec/eth-docker/traefik-cf.yml 'services.traefik.command[+]' certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=86400
  - sed -i 's/certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck/--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck/g' /home/ec/eth-docker/traefik-cf.yml
  - chown ec:docker -R /home/ec/eth-docker
  - sudo timedatectl set-ntp no
  - sudo apt update && sudo apt install ntp -y
  - cd /home/ec/eth-docker && docker-compose build --pull
  - cd /home/ec/eth-docker && ./ethd start
